In [11]:
# https://www.youtube.com/watch?v=G7FIQ9fXl6U&list=PLM8wYQRetTxBkdvBtz-gw8b9lcVkdXQKV&index=8
# Also, see lec 2 in word document on markov process in Wk 3 of Adv. Pred.Ana. in UEL folder 

import numpy as np

# 3 states, burger (0), pizza (1), hotdog (2)



In [13]:
#Create a dictionary to Assign states 

state = {
    0 : "Burger",
    1 : "Pizza",
    2 : "Hotdog"
}
state

{0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}

In [16]:
#create transition prob. matrix (tpm)

mat_A = np.array([[0.2, 0.6, 0.2],
             [0.3, 0.0, 0.7], 
             [0.5, 0.0, 0.5]])                        # we use the np.array func, and enter arguments by row

mat_A

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

In [18]:
#Simulating a random walk on the markov chain

n=15 #in the R practice this might have been n_t (from markov cohort 2_2)
start_state = 0
print(state[start_state], "--->", end = " ")       # prints the name of the starting state. so for e.g in dictionary above: state[0] corresponds to "Burger"
prev_state = start_state                          # The end=" ": prevents a newline character from being printed, allowing subsequent states to be printed on the same line.

while n-1:
    curr_state = np.random.choice([0, 1, 2], p = mat_A[prev_state])       # from np manual (https://numpy.org/doc/2.1/reference/random/generated/numpy.random.choice.html) -> random.choice(a, size=None, replace=True, p=None); here p = mat_A....
                                                                          #so basically, the func randomly choses from the 1D array of states, based on the tpm associated with the elements in the 1D array ([0,1,2])
                                                                          # prv_state is in the while loop as equal to the curr_state. However, as at n-1 =14, the prv_state = start_state (@ n=15) = 0
                                                                          # therefore, at this point in the code, we are essentially saying mat_A[0] = [0.2, 0.6, 0.2]. so make a random choice from 1D array of states based on a previous state being burger as written at the start (before the while loop)
    
    print(state[curr_state], "--->", end = " ")                           # Then pass the new "curr_state" to the dictionarry (in the 2nd cell above), print out result.
    prev_state = curr_state                                               # By the time the system reads the end of the while loop, prev_state will be equal to curr_state, and then the next step starts (n=13); this iterates WHILE "n-1" (Basically n-1 in the while loop means that we should continue till n<1)
    n-=1
print("stop")

Burger ---> Hotdog ---> Hotdog ---> Hotdog ---> Hotdog ---> Burger ---> Burger ---> Pizza ---> Hotdog ---> Hotdog ---> Hotdog ---> Burger ---> Burger ---> Pizza ---> Hotdog ---> stop


In [19]:
#let's simulate again but try using a differnt starting state (e.g. hotdog)

n=15 
start_state = 2
print(state[start_state], "--->", end = " ")       # prints the name of the starting state. so for e.g in dictionary above: state[0] corresponds to "Burger"
prev_state = start_state                          # The end=" ": prevents a newline character from being printed, allowing subsequent states to be printed on the same line.

while n-1:
    curr_state = np.random.choice([0, 1, 2], p = mat_A[prev_state])       
    print(state[curr_state], "--->", end = " ")                           
    prev_state = curr_state                                              
    n-=1
print("stop")

Hotdog ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> Hotdog ---> Burger ---> Pizza ---> Hotdog ---> stop


In [21]:
#finding the stationary Prb distribution of the markov chain (Approach 1: Monte Carlo Simulation)

steps = 10**6
start_state = 0
pi = np.array([0, 0, 0])          #at this point we set up for a count of total number of occurence of each state on the state space
pi[start_state] = 1        #basically the staring state pi[0] = certainly burger = 100%
prev_state = start_state

i = 0
while i<steps:
    curr_state = np.random.choice([0, 1, 2], p = mat_A[prev_state])
    pi[curr_state] +=1    #counts freq of current state + 1
    prev_state = curr_state
    i +=1
    
print("π = ", pi/steps)

# accuracy of the final answer increases asso. of steps increases


π =  [0.351584 0.210855 0.437562]


In [22]:
#finding the stationary Prb distribution of the markov chain (Approach 2: Repeated Matrix Multiplication)
#Basically finding the stationary tpm by multilplyin the initial matrix by itself until no change (see word doc on markov process wk3, UEL)

steps = 10**3
mat_A_n = mat_A

i=0
while i<steps:
    mat_A_n = np.matmul(mat_A_n, mat_A)  #Matrix product of two arrays.
    i+=1

print("mat_A^n = \n", mat_A_n, "\n")
print("π = ", mat_A_n[0])

#This approach is much faster

mat_A^n = 
 [[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]] 

π =  [0.35211268 0.21126761 0.43661972]


In [24]:
#finding the stationary Prb distribution of the markov chain (Approach 3: finding the left eigenvector)

import scipy.linalg     # This line imports the linalg module from the scipy (Scientific Python) library.  scipy provides many useful functions for scientific computing, including linear algebra.
values, left = scipy.linalg.eig(mat_A, right = False, left = True)  # This is the core of the code.  It calls the scipy.linalg.eig function with the ff arguments:
                                                                    # we know mat_A is the input tpm. "right=False": This argument tells the function not to calculate the right eigenvectors. Right eigenvectors are often calculated, but in this case, the code explicitly sets right=False because it only needs the left eigenvectors.
                                                                    # left=True: This argument tells the function to calculate the left eigenvectors.
                                                                    # values: A 1D array containing the eigenvalues of mat_A.
                                                                    # left: A 2D array where the columns are the left eigenvectors of mat_A.
        
print("left eigen vectors = \n", left, "\n")  
print("eigen values = \n", values)

left eigen vectors = 
 [[-0.58746336+0.j         -0.16984156-0.35355339j -0.16984156+0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467+0.35355339j -0.50952467-0.35355339j]] 

eigen values = 
 [ 1.  +0.j        -0.15+0.3122499j -0.15-0.3122499j]


In [25]:
# In the cell above we see that only the first column contains real numbers in both the left eigen vector and eigen values output

# We also see that the left eigen vectors are negative and do not sum up to 1 as it should

#so? We normalise


pi = left[:,0]              #notation selects all rows and only first column (indexed at 0) in "left" (from "values, left = scipy.linalg.eig" above)
pi_normalised = [(x/np.sum(pi).real) for x in pi]     # np.sum(pi).real: This calculates the sum of the elements of pi and takes the real part. Because of floating point calculations, even if the components of pi should be real, there could be a tiny, imaginary component. Taking the real part is a way to address this.
                                                      # (x/np.sum(pi).real): Each element x of pi is divided by the sum of all elements in pi, effectively normalizing the vector so that its elements sum to 1.
                                                      # [...]: The list comprehension creates a new list pi_normalised containing the normalized elements.
pi_normalised


#output is accurate and identical to other approaches. Instructor identifies approach as most accurate and preferred 

[(0.35211267605633795-0j), (0.21126760563380292-0j), (0.43661971830985913-0j)]

In [26]:
#### Now how abt computing the Prb for a specific sequence?   #####
#*** Pizza = P, Hotdog = H, Burger = B

## Consider the ff  sequence:

# P(P -> H -> H -> B) =?

# i.e., => P(X_0  = P, X_1 = H, X_2 = H, X_3 = B)
#       => P(X_0) * P(X_1 | X_0) * P(X_2 | X_1) * P(X_3 | X_2)


def find_prob(seq, mat_A, pi):
    start_state = seq[0]
    prob = pi[start_state]
    prev_state = start_state
    for i  in range(1, len(seq)):
        curr_state = seq[i]
        prob *= mat_A[prev_state][curr_state]
        prev_state = curr_state
    return prob

print(find_prob([1, 2, 2, 0], mat_A, pi_normalised))

(0.036971830985915506+0j)
