In [8]:
#practice from figurefactory

import plotly.figure_factory as ff
import plotly.graph_objects as go

import numpy as np

N_st = 40
x_start, x_end = -600.0, 600.0
y_start, y_end = -600.0, 600.0
x = np.linspace(x_start, x_end, N_st)
y = np.linspace(y_start, y_end, N_st)
X, Y = np.meshgrid(x, y)
x_inj, y_inj = 0.0, 0.0
x_p1, y_p1 = -500.0, 500.0
x_p2, y_p2 = 500.0, 500.0
x_p3, y_p3 = 500.0, -500.0
x_p4, y_p4 = -500.0, -500.0
N_0 = 1
X_0 = float(x_inj + 10*np.cos(2*np.pi*N_0/N_st))
Y_0 = float(y_inj + 10*np.sin(2*np.pi*N_0/N_st))

# Compute the velocity field on the mesh grid
u = 44.68 * (X_0 / (X_0**2 + Y_0**2)) - (11.17 *(((X_0 + 500) / (((X_0 + 500)**2) + ((Y_0 - 500)**2))) + ((X_0 - 500) / (((X_0 - 500)**2) + ((Y_0 - 500)**2))) + ((X_0 - 500) / (((X_0 - 500)**2) + ((Y_0 + 500)**2))) + ((X_0 + 500) / (((X_0 + 500)**2) + ((Y_0 + 500)**2)))))

v = (44.68 * (Y_0 / (X_0**2 + Y_0**2))) - (11.17 *(((Y_0 - 500) / (((X_0 + 500)**2) + ((Y_0 - 500)**2))) + ((Y_0 - 500) / (((X_0 - 500)**2) + ((Y_0 - 500)**2))) + ((Y_0 + 500) / (((X_0 - 500)**2) + ((Y_0 + 500)**2))) + ((Y_0 + 500) / (((X_0 + 500)**2) + ((Y_0 + 500)**2))))) 

print(type(v), type(u))
# Create streamline figure
fig = ff.create_streamline(x, y, u, v, name='streamline')

# name='streamline'

# Add source point
fig.add_trace(go.Scatter(x=[x_inj], y=[y_inj],
                          mode='markers',
                          marker_size=14,
                          name='source point'))
fig.add_trace(go.Scatter(x=[x_p1], y=[y_p1],
                          mode='markers',
                          marker_size=14,
                          name='sink_1'))
fig.add_trace(go.Scatter(x=[x_p2], y=[y_p2],
                          mode='markers',
                          marker_size=14,
                          name='sink_2'))
fig.add_trace(go.Scatter(x=[x_p3], y=[y_p3],
                          mode='markers',
                          marker_size=14,
                          name='sink_3'))
fig.add_trace(go.Scatter(x=[x_p4], y=[y_p4],
                          mode='markers',
                          marker_size=14,
                          name='sink_4'))

fig.show()


<class 'float'> <class 'float'>


TypeError: object of type 'float' has no len()

In [3]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm

#--- Constants ---#
nx = 5                         # nx: number of time steps in 'x'
ny = 5                         # ny: number of time steps in 'y'
dx = 1 
dy = 0.5 
U = 10.0

lower_x = 0.0
lower_y = 0.0

#-----------------#

XY = []

phi  = np.zeros((nx, ny))       # potential function    matrix
psi  = np.zeros((nx, ny))       # stream    function    matrix

for j in range(0, ny):
    for i in range(0, nx):
        xi = i * dx + lower_x
        yi = j * dy + lower_y
        XY.append((xi, yi))
        #--  potential function  --#        
        phi[i][j] = U * xi 
        #--  stream function  --#
        psi[i][j] = U * yi

print("XY = ", XY, "\n\n")
print("Psi = ", psi)

XY =  [(0.0, 0.0), (1.0, 0.0), (2.0, 0.0), (3.0, 0.0), (4.0, 0.0), (0.0, 0.5), (1.0, 0.5), (2.0, 0.5), (3.0, 0.5), (4.0, 0.5), (0.0, 1.0), (1.0, 1.0), (2.0, 1.0), (3.0, 1.0), (4.0, 1.0), (0.0, 1.5), (1.0, 1.5), (2.0, 1.5), (3.0, 1.5), (4.0, 1.5), (0.0, 2.0), (1.0, 2.0), (2.0, 2.0), (3.0, 2.0), (4.0, 2.0)] 


Psi =  [[ 0.  5. 10. 15. 20.]
 [ 0.  5. 10. 15. 20.]
 [ 0.  5. 10. 15. 20.]
 [ 0.  5. 10. 15. 20.]
 [ 0.  5. 10. 15. 20.]]


In [9]:
#practice from figurefactory

import plotly.figure_factory as ff
import plotly.graph_objects as go

import numpy as np

N_st = 40
x_start, x_end = -600.0, 600.0
y_start, y_end = -600.0, 600.0
x = np.linspace(x_start, x_end, N_st)
y = np.linspace(y_start, y_end, N_st)
X, Y = np.meshgrid(x, y)
x_inj, y_inj = 0.0, 0.0
x_p1, y_p1 = -500.0, 500.0
x_p2, y_p2 = 500.0, 500.0
x_p3, y_p3 = 500.0, -500.0
x_p4, y_p4 = -500.0, -500.0
N_0 = 1
X_0 = float(x_inj + 10*np.cos(2*np.pi*N_0/N_st))
Y_0 = float(y_inj + 10*np.sin(2*np.pi*N_0/N_st))

# Compute the velocity field on the mesh grid
u = 44.68 * (X / (X**2 + Y**2)) - (11.17 *(((X + 500) / (((X + 500)**2) + ((Y - 500)**2))) + ((X - 500) / (((X - 500)**2) + ((Y - 500)**2))) + ((X - 500) / (((X - 500)**2) + ((Y + 500)**2))) + ((X + 500) / (((X + 500)**2) + ((Y + 500)**2)))))

v = (44.68 * (Y / (X**2 + Y**2))) - (11.17 *(((Y - 500) / (((X + 500)**2) + ((Y - 500)**2))) + ((Y - 500) / (((X - 500)**2) + ((Y - 500)**2))) + ((Y + 500) / (((X - 500)**2) + ((Y + 500)**2))) + ((Y + 500) / (((X + 500)**2) + ((Y + 500)**2))))) 


# Create streamline figure
fig = ff.create_streamline(x, y, u, v, name='streamline')

# name='streamline'

# Add source point
fig.add_trace(go.Scatter(x=[x_inj], y=[y_inj],
                          mode='markers',
                          marker_size=14,
                          name='source point'))
fig.add_trace(go.Scatter(x=[x_p1], y=[y_p1],
                          mode='markers',
                          marker_size=14,
                          name='sink_1'))
fig.add_trace(go.Scatter(x=[x_p2], y=[y_p2],
                          mode='markers',
                          marker_size=14,
                          name='sink_2'))
fig.add_trace(go.Scatter(x=[x_p3], y=[y_p3],
                          mode='markers',
                          marker_size=14,
                          name='sink_3'))
fig.add_trace(go.Scatter(x=[x_p4], y=[y_p4],
                          mode='markers',
                          marker_size=14,
                          name='sink_4'))

fig.show()